language: go

install:
- go get -tags=websocket -t -v ./...
- go install -tags=websocket -v ./...

script:
- go test -v ./netchan
- |
  $GOPATH/bin/pingpong pong tcp://:25000 pingpong 10 &
  sleep 1
  $GOPATH/bin/pingpong ping tcp://:25001 tcp://127.0.0.1:25000/pingpong 10 &
  wait
- |
  $GOPATH/bin/pingpong ipong tcp://:25000 pingpong 10 &
  sleep 1
  $GOPATH/bin/pingpong iping tcp://:25001 tcp://127.0.0.1:25000/pingpong 10 &
  wait

notifications:
  email: false
